package com.wealoha.thrift;

import org.apache.thrift.TServiceClient;
import org.apache.thrift.protocol.TProtocol;

/**
 * All IFace(subclass of TServiceClient) were generated by thrift.
 * We don't know their types. <br/>
 * Since they all extends super class TServiceClient,
 * construct a new Client need only just one line.<br/>
 *
 * @author javamonk
 */
public interface ThriftClientFactory<T extends TServiceClient> {

    /**
     * return a new client using protocol<br/>
     * <p/>
     * <code>
     * <pre>
     *     public TServiceClient makeClient(TProtocol protocol) {
     *         return new Client(protocol);
     *     }
     * </pre>
     * </code>
     */
    T createClient(TProtocol protocol);

}
